name: stackexchange_app
description: A new Flutter project.


publish_to: 'none'  


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

 
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  dio: ^4.0.6
  either_dart: ^0.3.0
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.3
  equatable: ^2.0.5
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0
  connectivity_plus: ^3.0.2
  flutter_html: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  mockito: ^5.3.1
  bloc_test: ^9.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/